name: Lix GHA Installer Action
description: Simple action to install Lix (the independent variant of the Nix package manager).
inputs:
  github_access_token:
    description: |
      A github token that is added as an entry on extra-access-tokens in nix.conf.

      By default, the `github.token` is configured. See https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      for a description of the default token's permissions.
  extra_nix_config:
    description: |
      Additional configuration text to append to nix.conf. See https://docs.lix.systems/manual/lix/2.90/command-ref/conf-file.html
      for a description of the config file format.
  lix_version:
    description: |
      The exact lix version to use (e.g. 2.93.2) or a URL to the Lix release (e.g.
      https://releases.lix.systems/lix/lix-2.92.0/lix-2.92.0-x86_64-linux.tar.xz).

      You should almost always use a version instead of the full URL.
runs:
  using: "composite"
  steps:
    - name: Cache installer
      uses: actions/cache@v4
      with:
        path: /tmp/lix-installer
        key: lix-installer-${{ runner.os }}-${{ runner.arch }}
    - name: Install Lix
      run: bash ${{ github.action_path }}/do-the-lix-thing
      shell: bash
      env:
        INPUT_GITHUB_ACCESS_TOKEN: "${{inputs.github_access_token}}"
        GITHUB_TOKEN: "${{github.token}}"
        INPUT_EXTRA_CONFIG: "${{inputs.extra_nix_config}}"
        INPUT_LIX_VERSION: "${{inputs.lix_version}}"
