name: Lix GHA Installer Action
description: Simple action to install Lix (the independent variant of the Nix package manager). 
runs:
  using: "composite"
  steps:
    - name: Install Lix
      run: bash ${{ github.action_path }}/do-the-lix-thing
      shell: bash
