name: "CI"
on:
  pull_request:
  push:
    branches:
      - "latest"

jobs:
  do-it:
    name: Testing the action works (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - macos-13 # Last x86_64
          - macos-14 # aarch64
          - macos-15 # aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: Printing some useful info
        shell: bash
        run: |
          (
          set -eux -o pipefail
          env | grep -i nix
          cat /etc/nix/nix.conf
          )
      - name: Doing some Nix stuff
        shell: bash
        run: |
          (
          set -eux -o pipefail
          echo "pp RUBY_DESCRIPTION" | nix-shell -p ruby --run ruby
          )
