name: "CI"
on:
  pull_request:
  push:
    branches:
      - "latest"

jobs:
  do-it:
    name: Testing the action works (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - macos-13 # Last x86_64
          - macos-14 # aarch64
          - macos-15 # aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          extra_nix_config: |
            extra-access-tokens = example.com=lix-gha-installer-extra-config-works
      - name: Printing some useful info
        shell: bash
        run: |
          (
          set -eux -o pipefail
          env | grep -i nix
          cat /etc/nix/nix.conf
          )
      - name: nix config show
        shell: bash
        run: |
          (
          set -eux -o pipefail
          nix --extra-experimental-features nix-command config show
          )
      - name: Checking kvm is setup
        shell: bash
        run: |
          (
            set -eu -o pipefail
            if test -e /dev/kvm; then
              echo "/dev/kvm is present."
              if test -e /dev/kvm; then
                echo "/dev/kvm is accessible."
                if (set -x; nix --extra-experimental-features nix-command config show | grep '^system-features =.*kvm'); then
                  echo "kvm is setup as a system feature."
                else
                  echo "kvm has not been setup as a system feature!"
                  echo "Aborting..."
                  exit 1
                fi
              else
                echo "/dev/kvm is not accessible!"
                echo "Aborting..."
                exit 1
              fi
            else
              echo "No /dev/kvm... this is possibly fine."
              (
                set -x
                uname -a
              )
            fi
          )
      - name: Doing some Nix stuff
        shell: bash
        run: |
          (
          set -eux -o pipefail
          nix --extra-experimental-features nix-command config show | grep lix-gha-installer-extra-config-works
          echo "pp RUBY_DESCRIPTION" | nix-shell -p ruby --run ruby
          )
